source 'https://rubygems.org' do
  gem 'cucumber', '2.1.0'
  gem 'rspec', '~>3.2.0'
  gem 'page-object'
  gem 'data_magic'
  gem 'require_all'
  gem 'watir'
  gem 'thor'
  gem 'pry'
  gem 'rest-client'
  gem 'browsermob-proxy'
  gem 'typhoeus'
  gem 'httparty'
  gem 'nokogiri'
  gem 'link-checker'
  gem 'faker'
end